"""
app.py - Social Media Content Creator + Chatbot (single-file)

Quick summary:
- Single-file Streamlit app that generates social-media posts & variants.
- Works without any API keys or paid services.
- Optional: If `transformers` + `torch` are installed and a small model can be loaded (distilgpt2 / tiny-gpt2),
  the app will use that model for generation. If the model import/download/inference fails, the app
  automatically falls back to a deterministic template-based generator. No unhandled exceptions.
- Chatbot tab supports follow-ups using the local model if present, otherwise deterministic transforms.
- Includes export (CSV/JSON), copy-to-clipboard, regenerate, and a demo unit-test.

How to run (in comments):
1. Create venv (optional):
   python -m venv venv
   source venv/bin/activate  # (or `venv\Scripts\activate` on Windows)

2. Install requirements:
   pip install -r requirements.txt

3. Run:
   streamlit run app.py

Enable optional transformer model:
- Install (optional): pip install transformers torch
- The app will try to load a small model (distilgpt2 or sshleifer/tiny-gpt2). It will download it if missing.
- If download fails, the app falls back to template generator automatically.

Top-of-file requirements snippet (also saved separately as requirements.txt):
# requirements.txt
streamlit
pandas
numpy
# Optional (install only if you want model-based generation):
# transformers
# torch
# Optional for better translation (fallbacks exist in code):
# googletrans

Notes on fallback behavior & limitations:
- If the local model is available, generation quality improves and a "confidence" score is shown.
- If not available, deterministic template engine uses multiple templates, keyword extraction,
  and heuristics to always produce usable output.
- The app does not call external paid APIs or require keys.

Author: Generated by ChatGPT (GPT-5 Thinking mini)
"""

from __future__ import annotations
import streamlit as st
import pandas as pd
import numpy as np
import json
import re
import time
import html
from typing import List, Dict, Any, Optional, Tuple
from datetime import datetime, timedelta

# Optional imports: transformers + torch may not be present.
MODEL_AVAILABLE = False
MODEL_NAME_TRIED = None
_tokenizer = None
_model = None

# Attempt to import optional packages
try:
    import torch  # type: ignore
    from transformers import AutoModelForCausalLM, AutoTokenizer  # type: ignore

    # Try a small model name list - prefer tiny models to speed up download
    SMALL_MODELS = ["sshleifer/tiny-gpt2", "distilgpt2"]

    for mname in SMALL_MODELS:
        try:
            MODEL_NAME_TRIED = mname
            # try loading tokenizer & model (this will download if not cached)
            tokenizer = AutoTokenizer.from_pretrained(mname)
            model = AutoModelForCausalLM.from_pretrained(mname)
            # If we reach here, model ready
            _tokenizer = tokenizer
            _model = model
            MODEL_AVAILABLE = True
            break
        except Exception as e:
            # try next model
            MODEL_AVAILABLE = False
            _tokenizer = None
            _model = None
            continue
except Exception:
    MODEL_AVAILABLE = False
    _tokenizer = None
    _model = None

# ------------------------------
# Utility & Fallback Generators
# ------------------------------

STOPWORDS = set(
    [
        "the", "and", "a", "an", "to", "for", "on", "in", "of", "is", "are", "with",
        "by", "from", "that", "this", "it", "be", "as", "at", "or", "your", "you",
        "we", "our", "us", "will", "can", "how", "what", "why", "if"
    ]
)

# Templates for fallback generator
HOOK_TEMPLATES = [
    "You won't believe this about {topic}!",
    "Quick tip about {topic}:",
    "Stop scrolling — {topic} made this easy.",
    "Here's the truth on {topic}:",
    "Little-known fact: {topic} can {action}.",
    "{topic} in under 30 seconds:",
]

CTA_TEMPLATES = [
    "Comment your thoughts 👇",
    "Save this post for later!",
    "Share with someone who needs this.",
    "Try it and tell me what happened.",
    "Follow for more tips like this.",
    "Click the link in bio to learn more.",
]

IMAGE_PROMPTS = [
    "Minimalist flat-lay of {topic} tools on a wooden desk",
    "Close-up portrait expressing emotion about {topic}",
    "Cinematic cityscape background with bold text about {topic}",
    "Simple colorful illustration representing {topic}",
]

VIDEO_SCRIPT_TEMPLATES = [
    "{hook} {one_line_action}. Then show result. End with CTA.",
    "Introduce problem about {topic}. Demonstrate solution in 2 steps. Finish with CTA.",
    "Hook viewer with a question. Show quick tip. End with call to action.",
]

HASHTAG_BASE = [
    "{kw}", "{kw}tips", "{kw}life", "{kw}hack", "{kw}tok", "{kw}daily", "{kw}guide"
]

PLATFORM_CHARACTER_LIMITS = {
    "Instagram": 2200,
    "YouTube Shorts": 5000,
    "Twitter/X": 500,  # X allows longer now; we'll still treat as short
    "LinkedIn": 1300,
    "Facebook": 63206,
    "TikTok": 1500
}

PLATFORM_BEST_TIMES = {
    "Instagram": ("Tuesday", 18),  # 6 PM
    "YouTube Shorts": ("Thursday", 12),  # Noon
    "Twitter/X": ("Wednesday", 9),
    "LinkedIn": ("Tuesday", 9),
    "Facebook": ("Saturday", 11),
    "TikTok": ("Friday", 19)
}


def clean_text(text: str) -> str:
    """Simple text cleaning."""
    return re.sub(r"\s+", " ", text).strip()


def extract_keywords(topic: str, max_keywords: int = 6) -> List[str]:
    """Very simple keyword extractor: split on non-words, filter stopwords and short tokens."""
    tokens = re.findall(r"\w+", topic.lower())
    tokens = [t for t in tokens if t not in STOPWORDS and len(t) > 2]
    if not tokens:
        # fallback: use words of topic
        tokens = re.findall(r"\w+", topic.lower())
    # prefer unique preserving order
    seen = set()
    kws = []
    for t in tokens:
        if t not in seen:
            seen.add(t)
            kws.append(t)
        if len(kws) >= max_keywords:
            break
    return kws


def generate_hashtags_from_keywords(keywords: List[str], desired: int = 8) -> List[str]:
    """Produce relevant-looking hashtags from keywords and simple rules."""
    tags = []
    for kw in keywords:
        base = re.sub(r"[^a-zA-Z0-9]", "", kw)
        if not base:
            continue
        # produce a few variants
        variants = [f"#{base}", f"#{base}tips", f"#{base}life", f"#{base}hack"]
        for v in variants:
            if v not in tags:
                tags.append(v)
            if len(tags) >= desired:
                break
        if len(tags) >= desired:
            break
    # ensure we have at least 5 tags
    extra = ["#viral", "#trending", "#learn", "#howto", "#tips"]
    i = 0
    while len(tags) < 5 and i < len(extra):
        tags.append(extra[i])
        i += 1
    return tags[:desired]


def truncate_to_length(text: str, max_chars: int) -> str:
    """Truncate gracefully at word boundary."""
    text = clean_text(text)
    if len(text) <= max_chars:
        return text
    # Try to cut at nearest sentence end before max_chars
    cut = text[:max_chars]
    last_period = cut.rfind(".")
    if last_period > int(max_chars * 0.6):
        return cut[: last_period + 1]
    # else cut at last space
    last_space = cut.rfind(" ")
    if last_space > 0:
        return cut[:last_space] + "…"
    return cut[:max_chars] + "…"


def estimate_reading_time(text: str) -> str:
    """Return estimated reading time as string (seconds or minutes)."""
    words = len(re.findall(r"\w+", text))
    wpm = 200  # words per minute
    minutes = words / wpm
    if minutes < 0.5:
        seconds = int(minutes * 60)
        return f"{seconds} sec"
    else:
        return f"{minutes:.1f} min"


# ------------------------------
# Model-based generation (optional)
# ------------------------------
def model_generate(prompt: str, max_length: int = 120, num_return_sequences: int = 1) -> List[str]:
    """Use transformer model to generate text (if available)."""
    if not MODEL_AVAILABLE or _model is None or _tokenizer is None:
        raise RuntimeError("Model not available")
    device = "cuda" if torch.cuda.is_available() else "cpu"
    _model.to(device)
    inputs = _tokenizer(prompt, return_tensors="pt").to(device)
    # keep generation conservative
    out = _model.generate(
        **inputs,
        max_length=min(max_length + len(inputs["input_ids"][0]), 400),
        do_sample=True,
        top_p=0.9,
        temperature=0.9,
        num_return_sequences=num_return_sequences,
        pad_token_id=_tokenizer.eos_token_id
    )
    results = []
    for o in out:
        txt = _tokenizer.decode(o, skip_special_tokens=True)
        # strip prompt prefix
        if txt.startswith(prompt):
            txt = txt[len(prompt):].strip()
        results.append(clean_text(txt))
    return results


# ------------------------------
# High-level generator (uses model if available else fallback)
# ------------------------------
def generate_variants(
    topic: str,
    platform: str,
    tone: str,
    length_pref: str,
    n_variations: int,
    target_keywords: str = ""
) -> List[Dict[str, Any]]:
    """Generate content variants. Always returns at least one variant."""
    topic_clean = clean_text(topic)
    keywords = extract_keywords(topic_clean, max_keywords=6)
    # Add user-provided keywords
    if target_keywords:
        user_kws = [k.strip("# ").lower() for k in re.split(r"[,\n;]+", target_keywords) if k.strip()]
        for uk in user_kws:
            if uk and uk not in keywords:
                keywords.insert(0, uk)
    # Determine character target
    char_limit = PLATFORM_CHARACTER_LIMITS.get(platform, 300)
    if length_pref == "Short (<=120 chars)":
        target_chars = 120
    elif length_pref == "Medium (120–300 chars)":
        target_chars = 300
    else:
        target_chars = min(800, char_limit)

    variants: List[Dict[str, Any]] = []
    # If model available, try to use it; otherwise fallback templates
    use_model = MODEL_AVAILABLE and _model is not None and _tokenizer is not None

    for i in range(max(1, n_variations)):
        try:
            if use_model:
                # Build a simple prompt
                prompt = (
                    f"Write a {tone.lower()} social media post about: {topic_clean}. "
                    f"Platform: {platform}. Length target chars: {target_chars}. "
                    f"Include a short hook, body, CTA, hashtags and a 2-line short video script.\n\nPost:\n"
                )
                outs = model_generate(prompt, max_length=min(400, target_chars + 120), num_return_sequences=1)
                post_text = outs[0] if outs else ""
                post_text = truncate_to_length(post_text, target_chars)
                confidence = min(0.95, 0.5 + 0.05 * len(post_text) / (target_chars + 1))
                confidence_label = f"model (conf {confidence:.2f})"
            else:
                # deterministic fallback
                # Choose templates by rotation
                hook_tpl = np.random.choice(HOOK_TEMPLATES)
                cta_tpl = np.random.choice(CTA_TEMPLATES)
                img_tpl = np.random.choice(IMAGE_PROMPTS)
                vscripts = np.random.choice(VIDEO_SCRIPT_TEMPLATES)
                # simple action placeholder
                action = "save time" if "save" in topic_clean.lower() else "get better results"
                hook = hook_tpl.format(topic=topic_clean, action=action)
                body_templates = [
                    f"{topic_clean} can be easier than you think. Here's a simple way: 1) Do this 2) Do that. {cta_tpl}",
                    f"Want to improve {topic_clean}? Start with a small habit: try this today. {cta_tpl}",
                    f"Short guide on {topic_clean}: avoid common mistakes and focus on one skill each day. {cta_tpl}"
                ]
                body = np.random.choice(body_templates).format(topic=topic_clean)
                post_text = f"{hook} {body}"
                post_text = truncate_to_length(post_text, target_chars)
                confidence_label = "template"
            # Hashtags and other props
            kws_for_tags = keywords if keywords else extract_keywords(topic_clean, max_keywords=4)
            hashtags = generate_hashtags_from_keywords(kws_for_tags, desired=8)
            first_line_hook = hook if 'hook' in locals() else truncate_to_length(post_text.split(".")[0], 80)
            cta = cta_tpl if 'cta_tpl' in locals() else np.random.choice(CTA_TEMPLATES)
            image_prompt = img_tpl.format(topic=topic_clean) if 'img_tpl' in locals() else f"Photo representing {topic_clean}"
            video_script = vscripts.format(hook=first_line_hook, topic=topic_clean, action=action) if 'vscripts' in locals() else f"{first_line_hook}\nShow steps quickly.\n{cta}"
            # posting time - simple rule
            best_day, best_hour = PLATFORM_BEST_TIMES.get(platform, ("Monday", 12))
            # Add slight variance
            best_hour_v = (best_hour + i) % 24
            suggested_datetime = f"{best_day} at {best_hour_v}:00"
            # stats
            char_count = len(post_text)
            read_time = estimate_reading_time(post_text)

            variants.append(
                {
                    "id": f"v{i+1}",
                    "post_text": post_text,
                    "hashtags": hashtags,
                    "first_line_hook": first_line_hook,
                    "cta": cta,
                    "image_prompt": image_prompt,
                    "video_script": video_script,
                    "posting_time": suggested_datetime,
                    "char_count": char_count,
                    "reading_time": read_time,
                    "confidence": confidence_label,
                    "platform": platform,
                    "tone": tone,
                }
            )
        except Exception as e:
            # Robust fallback: ensure at least one variant is returned even on error
            variants.append(
                {
                    "id": f"v{i+1}",
                    "post_text": f"{topic_clean} — quick tip. {np.random.choice(CTA_TEMPLATES)}",
                    "hashtags": ["#tip", "#social"],
                    "first_line_hook": topic_clean,
                    "cta": np.random.choice(CTA_TEMPLATES),
                    "image_prompt": f"Illustration of {topic_clean}",
                    "video_script": f"Hook: {topic_clean}\nAction: Show example\nCTA: Comment",
                    "posting_time": f"Anytime",
                    "char_count": 50,
                    "reading_time": "10 sec",
                    "confidence": "template",
                    "platform": platform,
                    "tone": tone,
                }
            )
    return variants


# ------------------------------
# Chatbot utilities (fallback transforms)
# ------------------------------
def shorten_text(text: str, platform: str) -> str:
    """Shortens text according to platform rules; deterministic."""
    limits = {
        "Twitter/X": 240,
        "Instagram": 2200,
        "LinkedIn": 300,
        "Facebook": 63206,
        "TikTok": 500,
        "YouTube Shorts": 300
    }
    maxc = limits.get(platform, 300)
    return truncate_to_length(text, maxc)


SYNONYMS_SIMPLE = {
    "good": ["great", "awesome", "solid"],
    "quick": ["fast", "rapid", "speedy"],
    "easy": ["simple", "straightforward", "effortless"],
    "improve": ["boost", "enhance", "upgrade"],
    "try": ["attempt", "experiment with", "give a shot"]
}


def make_funnier(text: str) -> str:
    """A simple deterministic 'make funnier' transformation (insert emoji, exaggerate)."""
    punchlines = ["😂", "😅", "🔥"]
    # insert a casual punchline at end of first sentence
    parts = re.split(r'([.!?])', text, maxsplit=1)
    if parts and len(parts) >= 1:
        first = parts[0]
        remainder = "".join(parts[1:]) if len(parts) > 1 else ""
        first = first + " " + np.random.choice(punchlines)
        return (first + remainder).strip()
    return text + " " + np.random.choice(punchlines)


def replace_synonyms(text: str) -> str:
    """Replace some words with synonyms deterministically."""
    words = text.split()
    new_words = []
    for w in words:
        key = re.sub(r"[^a-zA-Z]", "", w).lower()
        if key in SYNONYMS_SIMPLE:
            new_words.append(np.random.choice(SYNONYMS_SIMPLE[key]))
        else:
            new_words.append(w)
    return " ".join(new_words)


# Very tiny static urdu fallback dictionary for demonstration
URDU_DICT = {
    "hello": "ہیلو",
    "thanks": "شکریہ",
    "thank": "شکریہ",
    "friend": "دوست",
    "good": "اچھا",
    "great": "بہت اچھا",
    "tips": "مشورے",
    "how": "کیسے",
    "to": "کو",
    "learn": "سیکھیں",
    "your": "آپ کا",
    "follow": "فالو کریں",
    "comment": "تبصرہ کریں",
}


def translate_to_urdu_fallback(text: str) -> str:
    """Naive word-by-word translation using small dictionary fallback."""
    def tr_word(w):
        key = re.sub(r"[^a-zA-Z]", "", w).lower()
        if key in URDU_DICT:
            return URDU_DICT[key]
        return w
    return " ".join(tr_word(w) for w in text.split())


# ------------------------------
# Streamlit UI
# ------------------------------

st.set_page_config(page_title="Content Creator Chatbot (Offline)", page_icon="✨", layout="wide")
st.title("✨ Social Media Content Creator & Chatbot (Offline, single-file)")

# Sidebar inputs
with st.sidebar:
    st.header("Options")
    example_topics = [
        "How to grow on Instagram organically",
        "Quick productivity habits for remote workers",
        "Top 5 AI tools for creators",
        "Healthy meal prep for busy people",
    ]
    default_topic = example_topics[0]
    topic = st.text_area("Topic (required)", value=default_topic, height=120)
    st.markdown("Platform")
    platform = st.selectbox("Platform", ["Instagram", "YouTube Shorts", "Twitter/X", "LinkedIn", "Facebook", "TikTok"])
    tone = st.selectbox("Tone", ["Casual", "Professional", "Funny", "Inspirational", "Urgent"])
    length_pref = st.selectbox("Post length", ["Short (<=120 chars)", "Medium (120–300 chars)", "Long (300–800 chars)"])
    n_variations = st.slider("Number of variations", 1, 10, 3)
    target_keywords = st.text_input("Optional target keywords / hashtags (comma-separated)")
    st.markdown("---")
    st.write("Model status:")
    if MODEL_AVAILABLE:
        st.success(f"Local model available: {MODEL_NAME_TRIED}")
    else:
        st.info("Transformer model NOT available — fallback template engine will be used.")
    if st.button("Use example topic"):
        topic = np.random.choice(example_topics)
        st.experimental_rerun()
    st.markdown("---")
    st.write("Exports")
    # clipboard log stored in session state
    if "clipboard_log" not in st.session_state:
        st.session_state["clipboard_log"] = []
    if st.button("Clear clipboard log"):
        st.session_state["clipboard_log"] = []
        st.success("Clipboard log cleared.")
    if st.download_button(
        "Download clipboard log (JSON)",
        data=json.dumps(st.session_state["clipboard_log"], ensure_ascii=False, indent=2),
        file_name="clipboard_log.json",
        mime="application/json",
    ):
        pass

# Main area with tabs
tabs = st.tabs(["Generator", "Chatbot"])
gen_tab = tabs[0]
chat_tab = tabs[1]

# Session for generated variants and chat history
if "variants" not in st.session_state:
    st.session_state["variants"] = []
if "last_gen" not in st.session_state:
    st.session_state["last_gen"] = {}
if "chat_history" not in st.session_state:
    st.session_state["chat_history"] = []

# Generator tab
with gen_tab:
    col1, col2 = st.columns([1, 3])
    with col1:
        st.markdown("### Generate")
        generate_btn = st.button("Generate")
        clear_btn = st.button("Clear")
        export_csv = st.button("Export CSV")
        export_json = st.button("Export JSON")
    with col2:
        st.markdown("### Preview / Results")
        if clear_btn:
            st.session_state["variants"] = []
            st.success("Cleared generated variants.")
        if generate_btn:
            if not topic or not topic.strip():
                st.error("Please enter a topic before generating.")
            else:
                with st.spinner("Generating variants..."):
                    try:
                        variants = generate_variants(
                            topic=topic,
                            platform=platform,
                            tone=tone,
                            length_pref=length_pref,
                            n_variations=n_variations,
                            target_keywords=target_keywords
                        )
                        st.session_state["variants"] = variants
                        st.session_state["last_gen"] = {
                            "topic": topic,
                            "platform": platform,
                            "tone": tone,
                            "length_pref": length_pref,
                            "timestamp": datetime.utcnow().isoformat()
                        }
                        st.success(f"Generated {len(variants)} variant(s).")
                    except Exception as e:
                        st.error(f"Generation failed (unexpected). Using fallback variant. Error: {str(e)}")
                        st.session_state["variants"] = generate_variants(
                            topic=topic,
                            platform=platform,
                            tone=tone,
                            length_pref=length_pref,
                            n_variations=1,
                            target_keywords=target_keywords
                        )
        # Show variants
        for var in st.session_state.get("variants", []):
            with st.expander(f"Variant {var['id']} — ({var['confidence']})", expanded=False):
                st.markdown(f"**Platform**: {var['platform']}  \n**Tone**: {var['tone']}")
                st.text_area("Post text", value=var["post_text"], key=f"post_{var['id']}", height=150)
                st.write("**Suggested hashtags:**", " ".join(var["hashtags"]))
                st.write("**First-line hook:**", var["first_line_hook"])
                st.write("**CTA:**", var["cta"])
                st.write("**Image prompt:**", var["image_prompt"])
                st.write("**Short video script:**")
                st.code(var["video_script"])
                st.write("**Suggested posting time:**", var["posting_time"])
                st.write("**Stats:**", f"Chars: {var['char_count']} • Read: {var['reading_time']}")
                # Copy to clipboard and Regenerate buttons
                btn_col1, btn_col2, btn_col3 = st.columns([1, 1, 1])
                with btn_col1:
                    # Copy to clipboard via HTML + JS using components
                    copy_html = f"""
                    <div>
                    <button onclick="navigator.clipboard.writeText({json.dumps(var['post_text'])}).then(()=>{{document.getElementById('lbl_{var['id']}').innerText='Copied!'}})">
                      Copy post
                    </button>
                    <span id="lbl_{var['id']}" style="margin-left:8px;color:green;"></span>
                    </div>
                    """
                    st.components.v1.html(copy_html, height=40)
                    # Add to clipboard log when user clicks copy is not directly detectable, so we also offer a log button
                with btn_col2:
                    if st.button(f"Copy & Log {var['id']}", key=f"logcopy_{var['id']}"):
                        # emulate copy by adding to clipboard log
                        st.session_state["clipboard_log"].append({
                            "id": var["id"],
                            "post_text": var["post_text"],
                            "time": datetime.utcnow().isoformat()
                        })
                        st.success("Logged to clipboard_log (you still need to paste manually).")
                with btn_col3:
                    if st.button(f"Regenerate {var['id']}", key=f"regen_{var['id']}"):
                        # regenerate single variant deterministically by re-running generator for 1 variant
                        with st.spinner("Regenerating..."):
                            new_var = generate_variants(
                                topic=topic,
                                platform=platform,
                                tone=tone,
                                length_pref=length_pref,
                                n_variations=1,
                                target_keywords=target_keywords
                            )[0]
                            # replace in session_state
                            idx = next((i for i, vv in enumerate(st.session_state["variants"]) if vv["id"] == var["id"]), None)
                            if idx is not None:
                                st.session_state["variants"][idx] = new_var
                                st.experimental_rerun()
        # Exports
        if export_json and st.session_state.get("variants"):
            st.download_button(
                "Download JSON",
                data=json.dumps(st.session_state["variants"], ensure_ascii=False, indent=2),
                file_name="variants.json",
                mime="application/json"
            )
        if export_csv and st.session_state.get("variants"):
            df = pd.DataFrame(st.session_state["variants"])
            # flatten lists for hashtags
            if "hashtags" in df.columns:
                df["hashtags"] = df["hashtags"].apply(lambda x: " ".join(x) if isinstance(x, list) else x)
            st.download_button(
                "Download CSV",
                data=df.to_csv(index=False).encode("utf-8"),
                file_name="variants.csv",
                mime="text/csv"
            )

# Chatbot tab
with chat_tab:
    st.header("Chatbot (follow-up edits & translations)")
    st.write("Ask follow-up instructions about the latest generated content. Examples: 'make this funnier', 'shorten for Twitter', 'translate to Urdu', 'translate to English', 'replace synonyms'.")
    chat_col1, chat_col2 = st.columns([3, 1])
    with chat_col1:
        user_msg = st.text_input("Your message (to the assistant)", key="chat_input")
    with chat_col2:
        send = st.button("Send")
        clear_chat = st.button("Clear chat history")
    if clear_chat:
        st.session_state["chat_history"] = []
        st.success("Chat history cleared.")

    # Show history
    for turn in st.session_state["chat_history"]:
        st.markdown(f"**User:** {turn['user']}")
        st.markdown(f"**Assistant:** {turn['assistant']}")
        st.markdown("---")

    if send and user_msg:
        # Determine which variant to act on: default to first
        base_variant = st.session_state["variants"][0] if st.session_state.get("variants") else None
        input_text = base_variant["post_text"] if base_variant else topic
        assistant_response = ""
        # If model available, try to use it for response; otherwise deterministic transforms
        if MODEL_AVAILABLE:
            # Compose prompt instructing the model to transform the input_text
            prompt = f"Original post:\n{input_text}\n\nInstruction: {user_msg}\n\nTransformed post:\n"
            try:
                outs = model_generate(prompt, max_length=300, num_return_sequences=1)
                assistant_response = outs[0] if outs else "Sorry, I couldn't generate a response."
            except Exception as e:
                assistant_response = f"(model failed) {str(e)}"
        # Deterministic fallback transforms
        if not assistant_response or assistant_response.startswith("(model failed)"):
            # Basic instructions parsing:
            low = user_msg.lower()
            try:
                if "shorten" in low or "short" in low:
                    assistant_response = shorten_text(input_text, platform)
                elif "long" in low or "expand" in low or "longer" in low:
                    assistant_response = input_text + " " + " ".join([s for s in [
                        "Here's more detail: try adding one small habit daily to see improvement.",
                        "Break it into steps and commit to 5 minutes per day."
                    ]][:2])
                elif "funn" in low or "funny" in low:
                    assistant_response = make_funnier(input_text)
                elif "synonym" in low or "replace" in low:
                    assistant_response = replace_synonyms(input_text)
                elif "urdu" in low:
                    # optional: try googletrans if installed, else fallback
                    try:
                        from googletrans import Translator  # type: ignore
                        translator = Translator()
                        t = translator.translate(input_text, dest="ur")
                        assistant_response = t.text
                    except Exception:
                        assistant_response = translate_to_urdu_fallback(input_text)
                elif "translate" in low and "english" in low:
                    # naive: assume input might be Urdu -> do nothing efficient fallback
                    assistant_response = input_text
                elif "hashtags" in low:
                    kws = extract_keywords(topic or input_text, max_keywords=6)
                    assistant_response = " ".join(generate_hashtags_from_keywords(kws, desired=10))
                else:
                    # generic: echo instruction appended
                    assistant_response = f"(Template response) {user_msg}. Base: {truncate_to_length(input_text, 300)}"
            except Exception as e:
                assistant_response = f"An error occurred while transforming: {str(e)}"
        # Save to chat history
        st.session_state["chat_history"].append({"user": user_msg, "assistant": assistant_response})
        st.experimental_rerun()

# Footer / miscellaneous
st.markdown("---")
st.write("App info:")
st.write(f"Model available: {MODEL_AVAILABLE} ({MODEL_NAME_TRIED})")
st.write("This app works offline and does not require API keys. If you want model-based generation, install `transformers` and `torch` and restart the app.")

# Minimal unit-test/demo when run as script
def _demo_fallback():
    """Simple demo to validate fallback generator logic."""
    t = "Boost your morning productivity with 3 micro-habits"
    vs = generate_variants(t, platform="Instagram", tone="Casual", length_pref="Short (<=120 chars)", n_variations=2, target_keywords="productivity, morning")
    print("Demo generated variants:")
    for v in vs:
        print("-" * 20)
        print(v["post_text"])
        print("Hashtags:", v["hashtags"])
    return vs


if __name__ == "__main__":
    # Run a basic demo when invoked directly
    print("Running demo of fallback generator (no Streamlit UI).")
    try:
        demo = _demo_fallback()
        print("Demo success.")
    except Exception as ex:
        print("Demo failed:", ex)
